name: app1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.3+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  auto_route: ^9.2.2
  provider: ^6.1.2
  flutter_hooks: ^0.20.5
  talker_flutter: ^4.4.1
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.1
  file_picker: ^8.1.2
  path_provider: ^2.1.4
  flutter_archive: ^6.0.3
  lottie: ^3.1.3
  story: ^1.1.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  intl: ^0.19.0
  share_plus: ^10.0.3
  firebase_core: ^3.6.0
  firebase_remote_config: ^5.1.3
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.1
  in_app_review: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  auto_route_generator:
  build_runner:
  flutter_gen_runner:
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter_gen:
  output: lib/core/gen/
  line_length: 80

  integrations:
    lottie: true

flutter_native_splash:
  image: assets/images/icon_rounded.png
  color: '#FFFFFF'

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/icon.png"

flutter:

  uses-material-design: true

  assets:
     - assets/images/
     - assets/icons/
     - assets/lottie/
     - assets/fonts/phonk/
     - assets/fonts/prompt/
     - assets/fonts/Prosto One/

  fonts:
      - family: Phonk
        fonts:
          - asset: assets/fonts/phonk/phonk-contrast-demo.otf

      - family: Prompt
        fonts:
          - asset: assets/fonts/prompt/Prompt-Regular.ttf
          - asset: assets/fonts/prompt/Prompt-Bold.ttf
            weight: 700

      - family: Prosto One
        fonts:
          - asset: assets/fonts/Prosto One/ProstoOne-Regular.ttf

